language: node_js
node_js:
  - "6.11.4"

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - npm install && gulp
  - npm install && gulp test
